runtime: nodejs16
env_variables:
  MONGODB_URL: ${{ secrets.MONGODB_URL }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  NODEMAILER_USER: ${{ secrets.NODEMAILER_USER }}
  NODEMAILER_PASS: ${{ secrets.NODEMAILER_PASS }}
handlers:
- url: /.*
  secure: always
  script: auto
  http_headers:
    Access-Control-Allow-Origin: https://ddd120.github.io
    Access-Control-Allow-Credentials: true
